/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserEntity } from '../models/user-entity';
export interface ChatEntity {
  id: number;
  name: string;
  owner: UserEntity;
}
