/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChatEntity } from '../models/chat-entity';
import { UserEntity } from '../models/user-entity';
export interface ConnectionEntity {
  chat?: ChatEntity;
  connectedWith: UserEntity;
  id: number;
  owner: UserEntity;
  state: string;
}
