/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ThreadEntity } from '../models/thread-entity';
import { UserEntity } from '../models/user-entity';
export interface ConnectionEntity {
  alias: string;
  chat?: ThreadEntity;
  connectedWith: UserEntity;
  id: number;
  owner: UserEntity;
  state: string;
}
