/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ThreadEntity } from './thread-entity';
import { UserEntity } from './user-entity';
export interface ConnectionEntity {
  chat?: ThreadEntity;
  connectedWith: UserEntity;
  id: number;
  owner: UserEntity;
  state: string;
}
