/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RecipientList } from '../models/recipient-list';
export interface CreateCommentDto {
  content: string;
  iv: string;
  post_id: number;
  recipients: Array<RecipientList>;
  sender_fingerprint: string;
}
