/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RecipientList } from '../models/recipient-list';
export interface CreatePostDto {
  chat_id: number;
  data: string;
  days_to_live?: number;
  iv: string;
  message: string;
  nsfw?: boolean;
  recipients: Array<RecipientList>;
  sender_fingerprint: string;
}
