/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DecryptionKeyEntity {
  encrypted_key: string;
  id: number;
  recipient_fingerprint: string;
}
