/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DecryptionKeyEntity } from '../models/decryption-key-entity';
import { ThreadEntity } from '../models/thread-entity';
export interface PostDto {
  created_at: number;
  data: string;
  days_to_live: number;
  decryptionKeys: Array<DecryptionKeyEntity>;
  id: number;
  iv: string;
  message: string;
  nsfw: boolean;
  sender_fingerprint: string;
  thread: ThreadEntity;
}
