/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommentEntity } from '../models/comment-entity';
import { LikeEntity } from '../models/like-entity';
import { PostDecryptionKeyEntity } from '../models/post-decryption-key-entity';
import { ThreadEntity } from '../models/thread-entity';
export interface PostDto {
  comments: Array<CommentEntity>;
  created_at: number;
  data: string;
  days_to_live: number;
  decryptionKeys: Array<PostDecryptionKeyEntity>;
  id: number;
  iv: string;
  likes: Array<LikeEntity>;
  message: string;
  nsfw: boolean;
  sender_fingerprint: string;
  thread: ThreadEntity;
}
