/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserEntity } from './user-entity';

export interface ThreadEntity {
  id: number;
  name: string;
  owner: UserEntity;
  participants: Array<UserEntity>;
}
