/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { shareControllerHandleShare } from '../fn/share/share-controller-handle-share';
import { ShareControllerHandleShare$Params } from '../fn/share/share-controller-handle-share';

@Injectable({ providedIn: 'root' })
export class ApiShareService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `shareControllerHandleShare()` */
  static readonly ShareControllerHandleSharePath = '/api/share';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `shareControllerHandleShare()` instead.
   *
   * This method doesn't expect any request body.
   */
  shareControllerHandleShare$Response(params?: ShareControllerHandleShare$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return shareControllerHandleShare(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `shareControllerHandleShare$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  shareControllerHandleShare(params?: ShareControllerHandleShare$Params, context?: HttpContext): Observable<void> {
    return this.shareControllerHandleShare$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
