/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { delete$ } from '../fn/post/delete';
import { Delete$Params } from '../fn/post/delete';
import { getAllPosts } from '../fn/post/get-all-posts';
import { GetAllPosts$Params } from '../fn/post/get-all-posts';
import { getPostsInThread } from '../fn/post/get-posts-in-thread';
import { GetPostsInThread$Params } from '../fn/post/get-posts-in-thread';
import { like } from '../fn/post/like';
import { Like$Params } from '../fn/post/like';
import { PostDto } from '../models/post-dto';
import { publish } from '../fn/post/publish';
import { Publish$Params } from '../fn/post/publish';

@Injectable({ providedIn: 'root' })
export class ApiPostService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllPosts()` */
  static readonly GetAllPostsPath = '/api/post/all';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllPosts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllPosts$Response(params?: GetAllPosts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PostDto>>> {
    return getAllPosts(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllPosts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllPosts(params?: GetAllPosts$Params, context?: HttpContext): Observable<Array<PostDto>> {
    return this.getAllPosts$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<PostDto>>): Array<PostDto> => r.body)
    );
  }

  /** Path part for operation `getPostsInThread()` */
  static readonly GetPostsInThreadPath = '/api/post/thread';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPostsInThread()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPostsInThread$Response(params: GetPostsInThread$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PostDto>>> {
    return getPostsInThread(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPostsInThread$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPostsInThread(params: GetPostsInThread$Params, context?: HttpContext): Observable<Array<PostDto>> {
    return this.getPostsInThread$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<PostDto>>): Array<PostDto> => r.body)
    );
  }

  /** Path part for operation `publish()` */
  static readonly PublishPath = '/api/post/publish';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publish()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  publish$Response(params: Publish$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return publish(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publish$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  publish(params: Publish$Params, context?: HttpContext): Observable<void> {
    return this.publish$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `like()` */
  static readonly LikePath = '/api/post/like';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `like()` instead.
   *
   * This method doesn't expect any request body.
   */
  like$Response(params: Like$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return like(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `like$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  like(params: Like$Params, context?: HttpContext): Observable<void> {
    return this.like$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `delete()` */
  static readonly DeletePath = '/api/post';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `delete()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete$Response(params: Delete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return delete$(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `delete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete(params: Delete$Params, context?: HttpContext): Observable<void> {
    return this.delete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
