/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateThreadRequest } from '../../models/create-thread-request';
import { ThreadEntity } from '../../models/thread-entity';

export interface CreateThread$Params {
      body: CreateThreadRequest
}

export function createThread(http: HttpClient, rootUrl: string, params: CreateThread$Params, context?: HttpContext): Observable<StrictHttpResponse<ThreadEntity>> {
  const rb = new RequestBuilder(rootUrl, createThread.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ThreadEntity>;
    })
  );
}

createThread.PATH = '/api/thread/new';
