/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ThreadEntity } from '../../models/thread-entity';

export interface GetThread$Params {
  threadId: any;
}

export function getThread(http: HttpClient, rootUrl: string, params: GetThread$Params, context?: HttpContext): Observable<StrictHttpResponse<ThreadEntity>> {
  const rb = new RequestBuilder(rootUrl, getThread.PATH, 'get');
  if (params) {
    rb.query('threadId', params.threadId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ThreadEntity>;
    })
  );
}

getThread.PATH = '/api/thread';
