/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IdsPage } from '../../models/ids-page';

export interface GetAllPostIds$Params {
  page: number;
  limit: number;
  excludeThreads?: Array<number>;
}

export function getAllPostIds(http: HttpClient, rootUrl: string, params: GetAllPostIds$Params, context?: HttpContext): Observable<StrictHttpResponse<IdsPage>> {
  const rb = new RequestBuilder(rootUrl, getAllPostIds.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('excludeThreads', params.excludeThreads, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IdsPage>;
    })
  );
}

getAllPostIds.PATH = '/api/post/all/ids';
