/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChallengeBodyDto } from '../../models/challenge-body-dto';
import { ChallengeVerifyDto } from '../../models/challenge-verify-dto';

export interface VerifyChallenge$Params {
      body: ChallengeBodyDto
}

export function verifyChallenge(http: HttpClient, rootUrl: string, params: VerifyChallenge$Params, context?: HttpContext): Observable<StrictHttpResponse<ChallengeVerifyDto>> {
  const rb = new RequestBuilder(rootUrl, verifyChallenge.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ChallengeVerifyDto>;
    })
  );
}

verifyChallenge.PATH = '/api/auth/verify-challenge';
